### ISSUE TITLE
Example of win_table_vcf

### ISSUE THREAD

**Issue by lincj1994** [TheJacksonLaboratory/canineglioma#4]
Here is the code you provided.
```
## Get winning tables from vcfs
cg_win_table <- mk_win_table(win_table_cg_vcf)
pg_win_table <- mk_win_table(win_table_pg_vcf)
ag_win_table <- mk_win_table(win_table_ag_vcf)
```
I'm wondering if you could provide an example data of win_table_vcf so that I can run the code estimating the molecular timing.

**Comment by sbamin** [comment]
hi @lincj1994, you will be able to get respect `win_table_{cg,pg,ag}_vcf` R objects using a guide at https://canineglioma.verhaaklab.com/figures/a1_preload/#load-r-objects Please open this issue again if you are unable to resolve this issue.
